local c = require("colorschemes.davedark.palette").c

return {
  ---------------------------------------------------------
  -- Treesitter
  ---------------------------------------------------------
  ["@boolean"] = { link = "Boolean" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@comment"] = { link = "Comment" },
  ["@conditional"] = { link = "Conditional" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = c.test_green },
  ["@constant.macro"] = { link = "Define" },
  ["@constructor"] = { link = "Special" },
  ["@debug"] = { link = "Debug" },
  ["@define"] = { link = "Define" },
  ["@exception"] = { link = "Exception" },
  ["@field"] = { fg = c.red },
  ["@float"] = { link = "Float" },
  ["@function"] = { fg = c.blue },
  ["@function.builtin"] = { fg = c.cyan },
  ["@function.macro"] = { link = "Macro" },
  ["@include"] = { fg = c.none },
  ["@keyword"] = { link = "Keyword" },
  ["@label"] = { link = "Label" },
  ["@macro"] = { link = "Macro" },
  ["@namespace"] = { link = "Identifier" },
  ["@method"] = { fg = c.none },
  ["@number"] = { link = "Number" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { link = "Identifier" },
  ["@preproc"] = { link = "PreProc" },
  ["@property"] = { link = "Identifier" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { link = "Delimeter" },
  ["@repeat"] = { link = "Statement" },
  ["@storageclass"] = { link = "StorageClass" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = c.test_green },
  ["@string.special"] = { fg = c.test_green },
  ["@structure"] = { link = "Structure" },
  ["@tag"] = { link = "Tag" },
  ["@text.literal"] = { link = "Comment" },
  ["@text.reference"] = { link = "Identifier" },
  ["@text.title"] = { link = "Title" },
  ["@text.todo"] = { link = "Todo" },
  ["@text.underline"] = { link = "Underlined" },
  ["@text.uri"] = { fg = c.green, underline = true },
  ["@type"] = { link = "Type" },
  ["@type.definition"] = { link = "TypeDef" },
  ["@variable"] = { fg = c.red },
}
